demo:
  outputs:
    dbt_zkan:
      type: bigquery
      method: service-account
      project: dataengineercafe
      dataset: dbt_zkan
      keyfile: dataengineercafe-data-quality-scoring-demo-c5d73068657c.json
      location: asia-southeast1
      fixed_retries: 1
      priority: interactive
      threads: 3
      timeout_seconds: 300

  target: dbt_zkan
